"""edited_timestamp

Revision ID: 2f91209a73a2
Revises: 36a9a018d4ba
Create Date: 2026-02-21 09:26:58.718458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f91209a73a2'
down_revision = '36a9a018d4ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_instance', schema=None) as batch_op:
        batch_op.drop_column('edited_timestamp')

    # ### end Alembic commands ###
