"""eggs_taken_home

Revision ID: 36a9a018d4ba
Revises: b3a94d816ad5
Create Date: 2025-05-03 07:40:00.554310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a9a018d4ba'
down_revision = 'b3a94d816ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_instance', schema=None) as batch_op:
        batch_op.alter_column('eggs', new_column_name='eggs_taken_home')
        batch_op.add_column(sa.Column('eggs_left_behind', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_instance', schema=None) as batch_op:
        batch_op.alter_column('eggs_taken_home', new_column_name='eggs')
        batch_op.drop_column('eggs_left_behind')

    # ### end Alembic commands ###
