"""specific_shift_instance_record

Revision ID: 4ad522e6d209
Revises: 7cefa57c0a76
Create Date: 2024-07-02 23:05:05.141427

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4ad522e6d209'
down_revision = '7cefa57c0a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specific_shift_instance_assignment',
                    sa.Column('specific_shift_instance_assignment_id', sa.Integer(), nullable=False),
                    sa.Column('time_of_day', sa.Integer(), nullable=False),
                    sa.Column('instance_date', sa.DateTime(), nullable=False),
                    sa.Column('instance_assigned_to', sa.String(length=128), nullable=False),
                    sa.PrimaryKeyConstraint('specific_shift_instance_assignment_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specific_shift_instance_assignment')
    # ### end Alembic commands ###
