"""shifts

Revision ID: 895e13b9c9c0
Revises: 7905fbc08853
Create Date: 2024-04-26 21:57:48.513108

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '895e13b9c9c0'
down_revision = '7905fbc08853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift',
                    sa.Column('shift_id', sa.Integer(), nullable=False),
                    sa.Column('day_of_week', sa.Integer(), nullable=False),
                    sa.Column('time_of_day', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('shift_id')
                    )
    op.create_table('shift_instance',
                    sa.Column('shift_instance_id', sa.Integer(), nullable=False),
                    sa.Column('shift_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['shift_id'], ['shift.shift_id'], ),
                    sa.PrimaryKeyConstraint('shift_instance_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_instance')
    op.drop_table('shift')
    # ### end Alembic commands ###
