"""sunrise_sunset

Revision ID: b3a94d816ad5
Revises: b421e42220ab
Create Date: 2025-03-09 03:03:19.475438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a94d816ad5'
down_revision = 'b421e42220ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sunrise_utc', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sunset_utc', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_instance', schema=None) as batch_op:
        batch_op.drop_column('sunset_utc')
        batch_op.drop_column('sunrise_utc')

    # ### end Alembic commands ###
