"""eggs

Revision ID: b421e42220ab
Revises: 4ad522e6d209
Create Date: 2024-08-21 21:41:22.764830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b421e42220ab'
down_revision = '4ad522e6d209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eggs', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_instance', schema=None) as batch_op:
        batch_op.drop_column('eggs')

    # ### end Alembic commands ###
