"""shift_instance_due_date

Revision ID: c5af58f7b116
Revises: 895e13b9c9c0
Create Date: 2024-04-27 17:03:29.934864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5af58f7b116'
down_revision = '895e13b9c9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_shift_person_id", 'person', ['person_id'], ['person_id'])

    with op.batch_alter_table('shift_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('completed_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_by', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_instance', schema=None) as batch_op:
        batch_op.drop_column('completed_by')
        batch_op.drop_column('completed_timestamp')
        batch_op.drop_column('due_date')

    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.drop_constraint("fk_shift_person_id", type_='foreignkey')
        batch_op.drop_column('person_id')

    # ### end Alembic commands ###
